format = """
$os\
$directory\
$git_branch\
$git_status\
$fill\
$python\
$lua\
$nodejs\
$golang\
$haskell\
$rust\
$ruby\
$package\
$aws\
$docker_context\
$custom\
$jobs\
$cmd_duration\
$line_break\
$character"""

add_newline = true
palette = 'catppuccin_mocha'

[os]
format = "[${symbol}]($style) "
style = "bold fg:blue"
disabled = false

[os.symbols]
Windows = " "
Ubuntu = " "
NixOS = " "
Raspbian = " "
Redhat = " "

[directory]
style = "bold fg:sapphire"
format = "[$path ]($style)"
truncation_length = 0
truncation_symbol = "…/"
fish_style_pwd_dir_length = 0
truncate_to_repo = false
home_symbol = "󰠦 "

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
style = "bold fg:yellow"
symbol = " "
format = "[on](white) [$symbol$branch ]($style)"

[git_status]
style = "bold fg:yellow"
format = "([$all_status$ahead_behind]($style) )"

[fill]
symbol = " "

[python]
style = "bold fg:teal"
symbol = " "
format = "[${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style)"
pyenv_version_name = true
pyenv_prefix = ""

[lua]
style = "bold fg:mauve"
symbol = " "

[nodejs]
style = "bold fg:sky"
symbol = " "

[golang]
style = "bold fg:sapphire"
symbol = " "

[haskell]
style = "bold fg:lavender"
symbol = " "

[rust]
style = "bold fg:peach"
symbol = " "

[ruby]
style = "bold fg:maroon"
symbol = " "

[package]
style = "bold fg:pink"
symbol = "󰏗 "

[aws]
symbol = " "
style = "bold fg:yellow"
format = "[$symbol($profile )(\\[$duration\\] )]($style)"

[docker_context]
symbol = " "
style = "bold fg:sapphire"
format = "[$symbol]($style) $path"
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]
detect_extensions = ["Dockerfile"]

[custom.ansible]
description = "Show Ansible icon when ansible-related files are detected"
command = 'echo "󱂚"'
style = "bold fg:sapphire"
format = "[ $output ]($style) $path"
when = '''
  [[ -f ansible.cfg ]] || [[ -f site.yml ]] || [[ -d roles ]] || ls *.yml *.yaml 2>/dev/null | grep -q -i ansible
'''

[jobs]
symbol = " "
style = "bold fg:red"
number_threshold = 1
format = "[$symbol]($style)"

[cmd_duration]
min_time = 100
style = "bold fg:overlay2"
format = "[$duration]($style)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
